### ISSUE TITLE
Fit handle within bounds

### ISSUE THREAD

**Issue by mrleblanc101** [vueform/slider#84]
How do we fit handle within the slider bound ?

![Screenshot 2024-03-11 at 3 54 58 PM](https://github.com/vueform/slider/assets/17392251/e3f67b83-c6bc-4e98-8e17-8d5b4c477026)

No-ui slider has an exemple for this [here](https://refreshless.com/nouislider/examples/#section-styling)

![Screenshot 2024-03-11 at 3 55 05 PM](https://github.com/vueform/slider/assets/17392251/58bfbff4-5d08-4801-a2ba-f440e7529426)
But adding padding like in the exemple doesn't seem to work.

**Comment by mrleblanc101** [comment]
By using the padding trick above, it looks like it is working at firs; the handle is aligned with the label.
![Screenshot 2024-03-11 at 4 03 41 PM](https://github.com/vueform/slider/assets/17392251/c078c82c-7926-4fb9-9b71-3d8242a55410)

But once you move the handle, you see that the background of the slider is not aligned properly.
![Screenshot 2024-03-11 at 4 03 48 PM](https://github.com/vueform/slider/assets/17392251/446c9669-7db8-4445-8b61-c3cd82d15ff0)

**Comment by mrleblanc101** [comment]
Seems like the noUiSlider doc was missing some things.
I found this issue: https://github.com/leongersen/noUiSlider/issues/1160#issuecomment-915094766
The fix is to move the background and radius on the parent.
```css
.slider-horizontal {
    padding: 0 8px;
    background-color: var(--slider-bg);
    border-radius: var(--slider-radius);
    .slider-connects {
        margin: 0 -8px;
        width: calc(100% + 16px);
    }
}
```
